name: Rebel Cars Game Server Nest CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Create Env File
        env:
          ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
        run: |
          echo "${ENV_FILE}" > .env

      - name: Build Application
        run: |
          # This creates the 'dist' folder for NestJS
          NODE_OPTIONS="--max-old-space-size=2048" npm run build

      - name: Copy Build Artifacts to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          # Copy the NestJS build folder, package files, and env vars
          source: "dist,package.json,package-lock.json,.env"
          target: "/home/rebelcars_io/@Server/RebelCarsNest"
          # Set to 0 so the files map directly into the target folder
          strip_components: 0

      - name: Install Prod Dependencies and Restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd /home/rebelcars_io/@Server/RebelCarsNest
            
            # Install only production dependencies on the server
            npm install --omit=dev --legacy-peer-deps

            # Start or reload the application using the NestJS entry point (dist/main.js)
            pm2 describe rebel-cars-nest-server > /dev/null && pm2 reload rebel-cars-nest-server || pm2 start dist/main.js --name "rebel-cars-nest-server"
            pm2 save
